### ISSUE TITLE
request few topics

### ISSUE THREAD

**Issue by purushottam858** [Android-for-Python/Android-for-Python-Users#1]
can you provide info related 

1)  emojis  display
2)  implement  languages other than English 
3)  Mapview 
4 )  apk security 
5)  To identify   which widget is displayed on screen 
6 )  Animation 
7)  Image processing

**Comment by Android-for-Python** [comment]
Don't know anything about 1-4
For 5, all I know is in the CameraXF and Face Detect examples.
