### ISSUE TITLE
What are the requirements need to be mentioned in buildozer for firebase-admin Python?

### ISSUE THREAD

**Issue by CodeWithVallabh** [Android-for-Python/Android-for-Python-Users#2]
I'm developing an app in Python Kivy which uses firebase-admin module also. So, please tell me the dependencies needed for firebase-admin to be mentioned in buildozer requirements

Like, ```import requests``` needs

```
requirements = python3,kivy==2.0.0,requests,urllib3,chardet,idna
```

in the buildozer.

**Comment by baseplate-admin** [comment]
Take a look at this


https://github.com/firebase/firebase-admin-python/blob/b9e95e8248eb1473ca5a13bf64e8a33b79dc9db3/setup.py#L39-L46

**Comment by Android-for-Python** [comment]
Or here https://github.com/Android-for-Python/cloud_storage_examples/tree/main/firebase_admin_example
