### ISSUE TITLE
EM_X86_64 (62) instead of EM_AARCH64 (183)

### ISSUE THREAD

**Issue by chriskeme** [Android-for-Python/Android-for-Python-Users#5]
I have a problem creating a mobile app with Kivy in python, using mediapipe. I followed the instructions on this forum but they didn't work.

The error is the following:

ImportError: dlopen failed: "/data/data/org.test.myapp/files/app/_python_bundle/site-packages/mediapipe/python/_framework_bindings.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)

**Comment by RobertFlatt** [comment]
Look here <https://github.com/Android-for-Python/Android-for-Python-Users#appendix-h--cryptic-error-messages>

And also the "Wheels" subsection here <https://github.com/Android-for-Python/Android-for-Python-Users#what-is-different-about-android>
