### ISSUE TITLE
Can import (and "implement") Java Abstract Classes

### ISSUE THREAD

**Issue by Julian-O** [Android-for-Python/Android-for-Python-Users#7]
In the section on Java Abstract Classes, the document says:

> It is not possible to import Java abstract classes or methods, as they have no implementation (abstract and implementation are Java keywords). And it it is not possible to provide the implementation in Python. You must write the implementation in Java and import that new class.

This confused me because, before I knew it was impossible, I went ahead and did this, and it worked!

[BroadcastReceiver](https://developer.android.com/reference/android/content/BroadcastReceiver) is, according to the documentation, 

    public abstract class BroadcastReceiver extends Object
    

Here is my code that imports, and provides an implementation in Python:

			from jnius import autoclass

			BroadcastReceiver = autoclass("android.content.BroadcastReceiver")
			AudioManager = autoclass("android.media.AudioManager")

			global subscribers
			subscribers = {}

			class _BecomingNoisyReceiver(BroadcastReceiver):
				def onReceive(self, context, intent):
					if AudioManager.ACTION_AUDIO_BECOMING_NOISY.equals(intent.getAction()):

						for callback in subscribers:
							callback(context, intent)

I don't know whether the document is wrong or whether I have misunderstood what it meant. I guess, strictly I have implemented a *subclass* not BroadcastReceiver itself, but I imported it fine.

**Comment by Android-for-Python** [comment]
Yes, that last sentence "You must.." says, perhaps not in the clearest way possible, what you did.

There is an example of this 3 subsections below https://github.com/Android-for-Python/Android-for-Python-Users#java-listener-class  , at a minimum adding a reference would be a good idea.

That section in turn references a full BroadcastReceiver (!) example nearby.  

EDIT: Users seem to make a mental distinction between implementing in Python and implementing in Java - using Pyjnius is viewed as implementing in Python. Implementing in Java is viewed as a different task - possibly unfamiliar language and buildozer options.  So the intent here was dismiss that second task and deal with it separately. Writing this document I have learned to never underestimate the inexperience of the users.

**Comment by Julian-O** [comment]
* I make a distinction between writing code that uses Python syntax and code that uses Java syntax (e.g. "public interface"). If you are suggesting that using pyjnius's autoclass and decorators is considered "writing the implementation in Java", then I think we need to edit the document to make the definitions clearer.

* About 3 years ago, I implemented a number of Listeners.
I did it differently to you. (I assume I pinched my approach from somewhere else online.) You have what is clearly Java code. I don't. I have some pyjnius references:

```
class OnAudioFocusChangeListener(PythonJavaClass):
    # https://developer.android.com/reference/android/media/
    #     AudioManager.OnAudioFocusChangeListener
    __javainterfaces__ = ("android/media/AudioManager$OnAudioFocusChangeListener",)

    def __init__(self, callback):
        super().__init__()
        self.callback = callback

    @java_method("(I)V")
    def onAudioFocusChange(self, focusChange):
        self.callback(focusChange)
``` 

This seems more straightforward than your approach (especially because I don't need to relearn Java syntax after successfully avoiding it since last century), but I know I am naïve in this domain, so I wonder if I am missing something!

* After implementing several listener interfaces, I spent hours and hours on dealing with BroadcastReceiver, because it looks and acts like a Listener class, but for some reason it wasn't defined in Android like all the other Listener classes. My first attempts to treat it the same failed. I needed to take a novel implementation approach.

So, when you point me to the Listener implementation, I go "No! No! This is different. For reasons I don't remember well."

Aside: I have only just clicked that it is the same class as in p4a's undocumented `android` package, and I should have used that instead. I am a bit mad about that.

**Comment by Android-for-Python** [comment]
There is more than one way to skin a cat. The 'best' way is often subjective.
