### ISSUE TITLE
Example of Pyjnius performance improvement

### ISSUE THREAD

**Issue by asrp** [Android-for-Python/Android-for-Python-Users#8]
The section [Pyjnius Performance](https://github.com/Android-for-Python/Android-for-Python-Users#pyjnius-performance) suggests

> The way to address this is to create a Java file that references the Java classes that were referenced with autoclass(). Then reference your Java class with autoclass(). 

Can you give an example of this? If I create `java/foo/bar/Imports.java` with 

	package foo.bar;
	import org.kivy.android.PythonActivity;

and add `android.add_src = java` in `buildozer.spec` then

	Imports = autoclass('foo.bar.Imports')
	Imports.PythonActivity

gives an attribute error. So merely importing doesn't expose the class. If I add

	public class Imports {
		public static Class PythonActivity = org.kivy.android.PythonActivity.class;
	}

to `Imports.java`, it makes `Imports.PythonActivity` a `Class`, not a `PythonActivity` and I can't find a way to use it.

**Comment by Android-for-Python** [comment]
> Then reference your Java class with autoclass().

Which is what you did.

Also this enhancement is exhibiting mission creep. A PR that fixed syntax errors, is expanding to address semantics. 
I am not open to this, however I did not explicitly set the scope at the beginning and that was my error.

**Comment by asrp** [comment]
I don't understand. It sounds like you're saying I applied the suggestion correctly. But it doesn't work. I don't know if its actually faster or not but the rest of the code wouldn't even run with the suggested replacement.

I'm not asking you to expand that paragraph into an example (unless you already had one readily available). I'm asking if you (still) think the suggestion there is correct and if so, why?

**Comment by Android-for-Python** [comment]
No comment.
